# Generated by Django 4.2.8 on 2024-01-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('aadhar_number', models.CharField(max_length=128, null=True)),
                ('district', models.CharField(max_length=128, null=True)),
                ('panchayath', models.CharField(max_length=128, null=True)),
                ('krishibhavan', models.CharField(max_length=128, null=True)),
                ('pincode', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandRegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irigation_facilities', models.CharField(blank=True, choices=[('Canal', 'canal'), ('Well', 'well')], max_length=128, null=True)),
                ('Area', models.CharField(blank=True, choices=[('Own Land', 'own land'), ('Leased Land', 'leased land'), ('Both', 'both')], max_length=128, null=True)),
                ('name_of_field', models.CharField(max_length=128, null=True)),
                ('crop_variety', models.CharField(blank=True, choices=[('Tomato', 'tomato'), ('Cardomom', 'cardomom'), ('Paddy', 'paddy')], max_length=128, null=True)),
                ('land_area', models.CharField(max_length=128, null=True)),
                ('survey_number', models.CharField(max_length=128, null=True)),
                ('tax_receipt_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pincode', models.CharField(max_length=15, null=True)),
                ('panchayath', models.CharField(max_length=128, null=True)),
                ('district', models.CharField(max_length=128, null=True)),
                ('state', models.CharField(max_length=128, null=True)),
                ('krishibhavan', models.CharField(max_length=128, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.landregistrationinfo')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
