# Generated by Django 4.2.8 on 2024-01-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='last_name',
        ),
    ]
