# Generated by Django 5.0.1 on 2024-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationinfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
