# Generated by Django 5.0.1 on 2024-01-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_landregistrationinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landinfo',
            old_name='phone_number',
            new_name='user_id',
        ),
    ]
