# Generated by Django 4.2.10 on 2024-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='website.button'),
        ),
    ]
