# Generated by Django 4.2.10 on 2024-03-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_button_chatmessage_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='buttons',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
    ]
